# Generated by Django 2.2 on 2021-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='status',
            field=models.BooleanField(),
        ),
    ]
