# Generated by Django 2.2 on 2021-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20211010_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
